---
- name: Create group and user for node app
  hosts: aws_ec2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Ensure python3 is installed
      raw: sudo apt-get update && sudo apt-get install -y python3
      register: install_python
      changed_when: install_python.rc == 0
      failed_when: install_python.rc != 0 and install_python.rc != 100
  tasks:
    - name: Create group for nodejs-user
      group:
        name: nodejs-user
    - name: Create linux user for node app
      user:
        name: nodejs-user
        comment: nodejs-user Admin
        group: nodejs-user
        groups: sudo
    - name: Reset SSH connection to apply new user/group changes
      ansible.builtin.meta: reset_connection

- name: Prepare EC2 instance for Node.js app
  hosts: aws_ec2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
    - name: Ensure app directory exists
      file:
        path: /home/nodejs-user/app
        state: directory
        owner: nodejs-user
        group: nodejs-user
        mode: '0755'

- name: Deploy nodejs app
  hosts: aws_ec2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: nodejs-app-1.0.0.tgz
        dest: /home/nodejs-user/app
        owner: nodejs-user
        group: nodejs-user
        extra_opts: [--strip-components=1]
    - name: Install dependencies
      npm:
        path: /home/nodejs-user/app
      environment:
        HOME: /home/nodejs-user
    - name: Ensure app files are owned by nodejs-user
      file:
        path: /home/nodejs-user/app
        state: directory
        recurse: yes
        owner: nodejs-user
        group: nodejs-user
    - name: Create systemd service for Node.js app
      copy:
        dest: /etc/systemd/system/nodejs-app.service
        content: |
          [Unit]
          Description=Node.js App
          After=network.target

          [Service]
          Type=simple
          User=nodejs-user
          WorkingDirectory=/home/nodejs-user/app
          ExecStart=/usr/bin/npm start
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      become: true

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      become: true

    - name: Start and enable Node.js app service
      systemd:
        name: nodejs-app
        state: started
        enabled: yes
      become: true
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug:
        msg: "{{ app_status.stdout_lines }}"
