---
- name: Configure nginx web server
  hosts: webserver
  tasks:
  - name: install nginx server
    apt:
      name: nginx=1.29*
      state: present
  - name: start nginx server
    service:
      name: nginx
      state: started
